### ISSUE TITLE
Automatically list-ify single references.

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-tools#43]
Often when writing parameter YAML files, we specify an object rather than a list of objects:

```yaml
reference:
  title: x
  href: y
```
instead of
```yaml
reference:
  - title: x 
    href: y
```

We should have a `f: ParameterNode -> ParameterNode` function that automatically applies this correction.
